apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-deployments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contactservice
  template:
    metadata:
      labels:
        app: contactservice
    spec:
      containers:
        - name: contactservice
          image: enzo3442/contact-service-dreamoove:latest
---
apiVersion: v1
kind: Service
metadata:
  name: contact-clusterip-server
spec:
  type: ClusterIP
  selector:
    app: contactservice
  ports:
    - name: contactservice
      protocol: TCP
      port: 80
      targetPort: 80