apiVersion: apps/v1
kind: Deployment
metadata:
  name: like-deployments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: likeservice
  template:
    metadata:
      labels:
        app: likeservice
    spec:
      containers:
        - name: likeservice
          image: enzo3442/like-service-dreamoove:latest
---
apiVersion: v1
kind: Service
metadata:
  name: like-clusterip-server
spec:
  type: ClusterIP
  selector:
    app: likeservice
  ports:
    - name: likeservice
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: likeservice
spec:
  type: LoadBalancer
  selector:
    app: likeservice
  ports:
  - port: 80
    targetPort: 8080