apiVersion: v1
kind: Service
metadata:
  name: dreamoove-service
  labels:
    name: dreamoove-service
    app: dreamoove-micro-services
spec:
  type: LoadBalancer
  ports: 
    - port: 80
      targetPort: 80
  selector: 
    name: dreamoove-api-pod
    app: dreamoove-micro-services