apiVersion: v1
kind: Pod
metadata:
  name: friend-api-pod
  labels:
    name: friend-api-pod
    app: dreamoove-micro-services
spec:
  containers:
    - name: friend-api
      image: dreamoove/friend-service:latest
      ports:
        - containerPort: 80
