apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployments
spec:
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    name: jenkins-service
    app: dreamoove-micro-services
spec:
  type: LoadBalancer
  ports: 
    - port: 80
      targetPort: 80
  selector: 
    name: jenkins-deployments
    app: dreamoove-micro-services