apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    name: jenkins-service
    app: dreamoove-micro-services
spec:
  type: LoadBalancer
  ports: 
    - port: 8080
      targetPort: 8080
  selector: 
    name: jenkins
    app: dreamoove-micro-services