apiVersion: v1
kind: Deployment
metadata:
  name: sport-api-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sport-api-pod
  template:
    metadata:
      labels:
        app: sport-api-pod
    spec:
      containers:
      - name: sport-api
        image: dreamoove/sport-service:latest
        ports:
        - containerPort: 80