apiVersion: v1
kind: Pod
metadata:
  name: sport-api-pod
  labels:
    name: user-api-pod
    app: dreamoove-micro-services
spec:
  containers:
    - name: sport-api
      image: dreamoove/sport-service:latest
      ports:
        - containerPort: 80
