apiVersion: v1
kind: Pod
metadata:
  name: user-api-pod
  labels:
    name: user-api-pod
    app: dreamoove-micro-services
spec:
  containers:
    - name: user-api
      image: dreamoove/user-service:latest
      ports:
        - containerPort: 80
