apiVersion: v1
kind: Pod
metadata:
  name: archive-api-pod-v2
  labels:
    name: archive-api-pod-v2
    app: dreamoove-micro-services
spec:
  containers:
    - name: archive-api-v2
      image: dreamoove/archive-service-v2:latest
      ports:
        - containerPort: 80
