apiVersion: v1
kind: Pod
metadata:
  name: commentary-api-pod
  labels:
    name: commentary-api-pod
    app: dreamoove-micro-services
spec:
  containers:
    - name: commentary-api
      image: dreamoove/commentary-service-v2:latest
      ports:
        - containerPort: 80
