apiVersion: v1
kind: Pod
metadata:
  name: commentary-api-pod-v2
  labels:
    name: commentary-api-pod-v2
    app: dreamoove-micro-services
spec:
  containers:
    - name: commentary-api-v2
      image: dreamoove/commentary-service-v2:latest
      ports:
        - containerPort: 80
