apiVersion: v1
kind: Pod
metadata:
  name: contact-api-pod-v2
  labels:
    name: contact-api-pod-v2
    app: dreamoove-micro-services
spec:
  containers:
    - name: contact-api-v2
      image: dreamoove/contact-service-v2:latest
      ports:
        - containerPort: 80
