apiVersion: v1
kind: Service
metadata:
  name: publication-service-v2
  labels:
    name: publication-service-v2
    app: dreamoove-micro-services
spec:
  type: LoadBalancer
  ports: 
    - port: 80
      targetPort: 80
  selector: 
    name: publication-api-pod-v2
    app: dreamoove-micro-services