apiVersion: v1
kind: Pod
metadata:
  name: sport-api-pod-v2
  labels:
    name: sport-api-pod-v2
    app: dreamoove-micro-services
spec:
  containers:
    - name: sport-api-v2
      image: dreamoove/sport-service-v2:latest
      ports:
        - containerPort: 80
