apiVersion: v1
kind: Pod
metadata:
  name: story-api-pod
  labels:
    name: story-api-pod
    app: dreamoove-micro-services
spec:
  containers:
    - name: story-api
      image: dreamoove/story-service-v2:latest
      ports:
        - containerPort: 80
